//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.RemoteTest.DistributedCacheService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistributedCacheService.INetCacheService")]
    public interface INetCacheService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetCacheService/AppendCache", ReplyAction="http://tempuri.org/INetCacheService/AppendCacheResponse")]
        string AppendCache(string key, object value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetCacheService/RemoveCache", ReplyAction="http://tempuri.org/INetCacheService/RemoveCacheResponse")]
        string RemoveCache(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetCacheService/ClearCache", ReplyAction="http://tempuri.org/INetCacheService/ClearCacheResponse")]
        string ClearCache();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetCacheService/GetCache", ReplyAction="http://tempuri.org/INetCacheService/GetCacheResponse")]
        object GetCache(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INetCacheServiceChannel : Console.RemoteTest.DistributedCacheService.INetCacheService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NetCacheServiceClient : System.ServiceModel.ClientBase<Console.RemoteTest.DistributedCacheService.INetCacheService>, Console.RemoteTest.DistributedCacheService.INetCacheService {
        
        public NetCacheServiceClient() {
        }
        
        public NetCacheServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NetCacheServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetCacheServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetCacheServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AppendCache(string key, object value) {
            return base.Channel.AppendCache(key, value);
        }
        
        public string RemoveCache(string key) {
            return base.Channel.RemoveCache(key);
        }
        
        public string ClearCache() {
            return base.Channel.ClearCache();
        }
        
        public object GetCache(string key) {
            return base.Channel.GetCache(key);
        }
    }
}
